### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by aik099** [shaos/rw3d#1]
The code is missing as is the website.

**Comment by shaos** [comment]
Yes, I know - I didn't start it yet :)

Basically it has to be mix of rw2d and Virtburg (my 3D engine from late 90s and early 00s that I didn't put into open-source yet)

**Comment by aik099** [comment]
I was thinking maybe it would be worth to rewrite the project using JavaScript/PHP (no pseudo robot language and compilation, just OOP) and HTML5 Canvas stuff so that more people can understand what's happening and making it more cross-platform. Right now it's Windows-only.

I've started looking at https://github.com/shaos/rw1o/blob/master/rw1_duel.cpp (I guess that is from where rw_duel.exe is created) yesterday and haven't understood much of what's happening to be able to rewrite it using different programming language. Probably too much C++ stuff with pointers for me web developer guy to understand.

**Comment by shaos** [comment]
JS is too slow for Interpreter+3D (and actually Robot Warfare is not Windows only - it's cross-platform with DOS, Windows and Linux ports). If you want "Robot Warfare 1" byte-code interpreter in JS then I can tell you that I already have it ;)

https://github.com/shaos/circuits_cc/tree/master/www

Basically it's self-modifying (self-extending) JS-program that generates chain of JS-functions based on RW0 byte-codes - this is a fastest possible way to run an interpreter in JS :)

**Comment by aik099** [comment]
We're not after any profits here, so 3D isn't needed. Main point of the game was to involve developers into writing robots and having fun. So we can stick with 2D.

Not sure if we should stick to meta-language and bytecode concepts any longer. Things like GOTO and LABEL are considered bad practice in modern language so advertising them as part of meta language won't teach developers any good practices ;)

**Comment by aik099** [comment]
Besides how you solved tick problem, where for example:

* there are 2 robots on the board
* each robot can either move or use radar and that costs them 1 tick
* in that 1 tick which of the robot command is executed 1st: the radar or move?

**Comment by shaos** [comment]
every tick engine will execute commands for each robot sequentially to fulfill the tick (it could be "free" commands, so current robot will run until it will get "heavy command" or if limit of "free" commands is exceeded)

P.S. May be better to create new project then instead of discussing it in the issue tracker of unrelated project that was about 3D robots? ;)

**Comment by shaos** [comment]
Just created under GPLv3 :)

https://github.com/shaos/rw1js

**Comment by aik099** [comment]
Good. Posted https://github.com/shaos/rw1js/issues/1 in there.

**Comment by shaos** [comment]
then this issue is closed :)
